---
- hosts: 192.168.100.29
  name: Apache PHP
  become: yes

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start and make Apache Persistent
      service:
        name: httpd
        state: started
        enabled: yes
