---
- hosts: 192.168.100.29
  name: Apache PHP
  become: yes

  tasks:
    - name: Disable Firewall on HTTP service
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: Enable Firewall Port 80 (HTTP)
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled

    - name: Enable Firewall Port 22 (SSH)
      firewalld:
        port: 22/tcp
        permanent: yes
        state: enabled

    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start and make Apache Persistent
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Deploy PHP - Apache
      copy:
        src: index.php
        dest: /var/www/html/index.php
        owner: manutencao
        group: root
        mode: 0644
